### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by MauriceHendrix**
## Description

Pinned sympy version to 1,4 in setup.py

## Motivation and Context

The different sympy version (1.5) the CI was pulling in was causing my tests to fail in CI but pass locally

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated all documentation necessary.
- [ ] I have checked spelling in (new) comments.
No new comments added

##Testing
- [X] Testing is done automaticly and codecov shows test coverage
- [ ] This cannot be tested automatically

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Shouldn't we be fixing cellmlmanip to work with sympy 1.5 instead?

Also we had some discussion before about pinning versions in setup.py (I'm having some trouble finding links to it!) and the conclusion was that we can pin things in `dev.txt` and similar (so that devs use the same version, which @jonc125 says is a good idea) but not in `setup.py` (because its a library so needs to work in several environments). 

Specifying a minimum version in `setup.py` is ok, or if there's a version of a dependency with a known bug you can disallow that version explicitly. But in this case it looks like sympy behaviour has changed so we need to update cellmlmanip to work with the new behaviour and bump the required version up to 1.5?

**Comment by MauriceHendrix** [comment]
> Shouldn't we be fixing cellmlmanip to work with sympy 1.5 instead?
> 
> Also we had some discussion before about pinning versions in setup.py (I'm having some trouble finding links to it!) and the conclusion was that we can pin things in `dev.txt` and similar (so that devs use the same version, which @jonc125 says is a good idea) but not in `setup.py` (because its a library so needs to work in several environments).
> 
> Specifying a minimum version in `setup.py` is ok, or if there's a version of a dependency with a known bug you can disallow that version explicitly. But in this case it looks like sympy behaviour has changed so we need to update cellmlmanip to work with the new behaviour and bump the required version up to 1.5?



> Shouldn't we be fixing cellmlmanip to work with sympy 1.5 instead?
> 
> Also we had some discussion before about pinning versions in setup.py (I'm having some trouble finding links to it!) and the conclusion was that we can pin things in `dev.txt` and similar (so that devs use the same version, which @jonc125 says is a good idea) but not in `setup.py` (because its a library so needs to work in several environments).
> 
> Specifying a minimum version in `setup.py` is ok, or if there's a version of a dependency with a known bug you can disallow that version explicitly. But in this case it looks like sympy behaviour has changed so we need to update cellmlmanip to work with the new behaviour and bump the required version up to 1.5?

No it needs to be the same version otherwise we get this situation where tests pass locally but not in CI. If you want we can do >=1.4 in the dev requirements instead though

**Comment by MichaelClerx** [comment]
> otherwise we get this situation where tests pass locally but not in CI.

That's a feature! You test locally in whatever, and then ideally CI tests in all other supported configurations (or some sensible subset). At the moment we're not doing this very thoroughly, but having setup.py say something like `>=1.4` will make it pull in new versions and alert us to issues with newer versions. If we had everything pinned it would hide this issue, not solve it

**Comment by MauriceHendrix** [comment]
> > otherwise we get this situation where tests pass locally but not in CI.
> 
> That's a feature! You test locally in whatever, and then ideally CI tests in all other supported configurations (or some sensible subset). At the moment we're not doing this very thoroughly, but having setup.py say something like `>=1.4` will make it pull in new versions and alert us to issues with newer versions. If we had everything pinned it would hide this issue, not solve it

I understand you want to cater for new versions, but this is not a good way to do it in my opinion.

**Comment by jonc125** [comment]
From Slack:
> What I normally do on projects, is have CI run tests at least twice: once with the pinned dev versions (so if it works locally it'll pass there) and also as an 'allowed failure' with latest versions. So you get alerted if a new version has just appeared that breaks things, but don't have to fix it immediately to merge a feature PR.
> If you're officially supporting multiple versions you can also run with those, and decide on priority as to whether they're allowed failures or not.

For this PR, I'd suggest either just merge (!) or fix by updating the Travis and AppVeyor config in weblab-cg to use the pinned versions, then in a second PR update the configs again to test both pinned & latest.

**Comment by jonc125** [comment]
@MichaelClerx says Cellmlmanip is tested with both so can use its config as an example.

**Pull request closed without merging**
