### PR TITLE
Make load_template() use posixpath (regardless of os)

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #11

Also handles #10

### CODE REVIEW

**Comment by MauriceHendrix** [comment]
Works fine on my win10 setup

**Comment by jonc125** [comment]
@MauriceHendrix rather than closing, my typical practice is for reviewers to add their review response (approve, comment, or request changes) then allow the PR owned to merge.

**Comment by MichaelClerx** [comment]
Tests pass, but no windows testing yet. Might set that up before we merge this?

@jonc125 does UCL have some kind of appveyor account so I don't have to do it in my own name?

**Comment by MauriceHendrix** [comment]
Tests pass on my own windows machine.
Travic ci seems to have windows but I'm not familiar with travic

**Comment by MichaelClerx** [comment]
> Tests pass on my own windows machine.
> Travic ci seems to have windows but I'm not familiar with travic

Thanks! The windows support on travis is still a bit experimental at the moment (unless it's changed in the last few weeks). Looking forward to when it supports it properly :-)

**Comment by jonc125** [comment]
> @jonc125 does UCL have some kind of appveyor account so I don't have to do it in my own name?

I have an appveyor account but probably don't have time to set up today. From what I recall it was a bit non-trivial to create institutional accounts, but it's about a year since I last played with it!

**Comment by MichaelClerx** [comment]
Thanks! I've just done it with my own account now, and it picks up the same bug @MauriceHendrix found. Can't merge it though, because the tests don't pass :laughing: 
Will merge this now and then rebase the appveyor one and try again

**Pull request merged**
